import { StyleSheet } from 'react-native';
import { Theme } from '../../../theme/Theme';
import { horizontalScale, verticalScale, moderateScale } from '../../../utils/responsive';

const H = horizontalScale;
const V = verticalScale;
const S = moderateScale;

const PAD = H(16);
const GAP = V(12);
const RADIUS = Theme.radius.lg;

export const createStyles = (activeColors) => StyleSheet.create({
  shell: { flex: 1, backgroundColor: activeColors.background },

  scrollContent: { paddingHorizontal: PAD, paddingTop: V(8), paddingBottom: V(170) },

  headerBlock: {
    alignItems: 'center',
    paddingVertical: V(22),
  },
  settingsBtn: {
    position: 'absolute',
    top: V(16),
    right: PAD,
    padding: 8,
  },
  avatarWrap: { position: 'relative', marginBottom: V(12) },
  avatarProfile: {
    width: S(90),
    height: S(90),
    borderRadius: S(45),
    borderWidth: 2.5,
    borderColor: activeColors.primary,
  },
  camBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: activeColors.primary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    width: H(28),
    height: H(28),
  },
  headerName: { color: activeColors.text, fontSize: S(20), fontWeight: '700' },
  headerRole: { color: activeColors.subtext, fontSize: S(13), marginTop: V(4) },
  scoreRow: { flexDirection: 'row', alignItems: 'center', marginTop: V(8), gap: 6 },
  scoreText: { color: activeColors.primary, fontSize: S(13), fontWeight: '600' },

  block: {
    backgroundColor: activeColors.card,
    borderRadius: RADIUS,
    padding: PAD,
    marginBottom: GAP,
    borderWidth: 1,
    borderColor: activeColors.border,
  },
  blockTitle: {
    color: activeColors.text,
    fontSize: S(13),
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: GAP,
    opacity: 0.9,
  },

  gridRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: GAP,
  },
  gridRowInner: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: H(10),
  },
  gridCol: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: H(12),
    paddingVertical: V(12),
    paddingHorizontal: H(12),
    borderRadius: 12,
    borderWidth: 1,
    borderColor: activeColors.border,
    backgroundColor: activeColors.surface,
  },
  gridIcon: {
    width: H(40),
    height: H(40),
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gridLabel: { color: activeColors.text, fontSize: S(13), fontWeight: '500', flex: 1 },

  iconRow: { flexDirection: 'row', justifyContent: 'space-between' },
  iconCol: { alignItems: 'center', width: '23%' },
  iconCircle: {
    width: H(48),
    height: H(48),
    borderRadius: H(24),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: activeColors.surface,
    borderWidth: 1,
    borderColor: activeColors.border,
    position: 'relative',
  },
  iconLabel: {
    color: activeColors.subtext,
    fontSize: S(11),
    textAlign: 'center',
    marginTop: V(6),
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#EF4444',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: { color: '#fff', fontSize: S(8), fontWeight: 'bold' },
  badgeDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: activeColors.primary,
    borderWidth: 1.5,
    borderColor: activeColors.background,
  },

  ratingRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: V(6),
  },
  ratingItem: { alignItems: 'center' },

  bottomActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    gap: H(10),
    paddingHorizontal: PAD,
    paddingVertical: V(14),
    borderTopWidth: 1,
    borderTopColor: activeColors.border,
    backgroundColor: activeColors.background,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: V(12),
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: activeColors.surface,
    borderColor: activeColors.border,
  },
  actionBtnText: { color: activeColors.text, fontSize: S(13), fontWeight: '600', marginLeft: H(6) },
  logoutText: { color: activeColors.primary },
  deleteText: { color: activeColors.text },

  fab: {
    position: 'absolute',
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  voucherFab: { bottom: V(105), right: H(16), width: 56, height: 56, backgroundColor: activeColors.primary },

  bottomTitle: { color: activeColors.text, fontSize: S(15), fontWeight: '600', marginBottom: V(12) },
  bottomInput: {
    borderWidth: 1,
    borderColor: activeColors.border,
    backgroundColor: activeColors.inputBg,
    color: activeColors.text,
    borderRadius: 12,
    paddingHorizontal: H(14),
    paddingVertical: V(12),
    fontSize: S(14),
    marginTop: V(8),
  },
  bottomSaveBtn: {
    borderRadius: 12,
    paddingVertical: V(13),
    alignItems: 'center',
    marginTop: V(18),
    backgroundColor: activeColors.primary,
  },
  bottomSaveBtnText: { color: '#fff', fontSize: S(15), fontWeight: '700' },
  chipRow: { flexDirection: 'row', gap: H(8), marginTop: V(8) },
  chip: {
    paddingHorizontal: H(16),
    paddingVertical: V(10),
    borderRadius: 10,
    borderWidth: 1,
    borderColor: activeColors.border,
    backgroundColor: activeColors.surface,
  },

  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: V(13),
    borderBottomWidth: 1,
    borderBottomColor: activeColors.border,
  },
  settingInfo: { flex: 1, marginRight: H(10) },
  settingTitleRow: { flexDirection: 'row', alignItems: 'center' },
  settingIcon: { marginRight: H(10) },
  settingTitle: { color: activeColors.text, fontSize: S(14), fontWeight: '600' },
  settingDesc: { color: activeColors.subtext, fontSize: S(12), marginTop: V(2), opacity: 0.8 },
  toggleWrap: { flexDirection: 'row', alignItems: 'center' },
  toggleLabel: { color: activeColors.subtext, marginRight: H(8), fontSize: S(13) },
  toggleTrack: {
    width: H(44),
    height: V(24),
    borderRadius: 12,
    padding: 2,
    justifyContent: 'center',
  },
  toggleThumb: {
    width: H(20),
    height: H(20),
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  thumbOn: { alignSelf: 'flex-end' },

  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: PAD,
    paddingVertical: V(14),
    borderBottomWidth: 1,
    borderBottomColor: activeColors.border,
    backgroundColor: activeColors.card,
  },
  modalTitle: {
    color: activeColors.text,
    fontSize: S(17),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  modalClose: { color: activeColors.primary, fontSize: S(16), fontWeight: '600' },
  modalBody: { flex: 1, padding: PAD, backgroundColor: activeColors.background },
  warningText: { color: activeColors.subtext, fontSize: S(12), marginTop: V(6) },
  logoutBtnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    padding: V(14),
    marginTop: V(20),
    borderWidth: 1,
    borderColor: activeColors.border,
    backgroundColor: activeColors.surface,
  },

  bsSectionTitle: { color: activeColors.text, fontSize: S(15), fontWeight: '600', marginBottom: V(10) },
  regionBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: activeColors.surface,
    borderWidth: 1,
    borderColor: activeColors.border,
    borderRadius: 12,
    padding: V(12),
    marginTop: V(8),
  },
  regionValue: { color: activeColors.text, fontSize: S(14), fontWeight: '600', marginTop: V(4) },

  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: activeColors.modalOverlay,
  },
});